# Netlify configuration for Soulful Space with custom domain support
[build]
  publish = "dist"
  command = "npm run build"

[build.command]
  NODE_VERSION = "18"

# Custom domain configuration
# Replace 'yourdomain.com' with your actual domain
[[redirects]]
  from = "https://soulfulspace.netlify.app/*"
  to = "https://soulfulspace.com/:splat"
  status = 301
  force = true

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom domain settings
[context.production]
  environment = { NODE_ENV = "production" }

# Branch deploys
[context.branch-deploy]
  command = "npm run build"

# Deploy previews
[context.deploy-preview]
  command = "npm run build"